# Computation Chapter

## Rationale

> Set scene for pedagogy and difficulty of melodies: It's the structure of the music

Music theorists use their experience and intuitions to build appropriate curricula for their aural skills pedagogy.
Teaching aural skills typically starts with providing students with simpler exercises, often employing a limited number of notes and rhythms, and then slowly progressing to more difficult repertoire. 
This progression from simpler to more difficult exercises is evident in aural skills text books.
Of the major aural skills textbooks such as the @ottmanMusicSightSinging2014, @berkowitzNewApproachSight2011, @karpinskiManualEarTraining2007, and @clelandDevelopingMusicianshipAural2010, each is structured in a way that musical material presented earlier on in the book is more manageable than that nearer the end.
In fact, this is true of almost any étude book: open to a random page in a book of musical studies and the difficulty of the study will likely scale accordingly to its relative position in the textbook.
But it is not a melody's position in a textbook that makes it difficult to perform: this difficulty comes from the structural elements from the music itself.

> Theorists intution for complexity can map to features

Intuitively, music theorists have a general understanding of what makes a melody difficult to dictate.^[I find it safe to assume that more complex melodies are more difficult to dictate As I will demonstrate in this chapter, a melody's complexity and difficulty to be dictated are closely related. For that reason, I will use the term complexity as a proxy for its ability to be  dictated.] 
Factors that might contribute to this complexity could range from the melody's note density, the intricacies of the rhythms involved, the scale from which the melody derives, or even more intuitively understood factors such as how tonal the melody sounds.
Although given all these factors, there is no definitive combination of features that perfectly predicts the degree to which theorists will agree how complex a melody is.
In many ways, questions of melodic complexity are very much like questions of melodic similarity: it depends on both who is asking the question and for what reasons [@cambouropoulosHowSimilarSimilar2009].

> Look, an example

Looking at the melodies presented in Figures X and Y, most aural skills pedagogues will be able to successfully intuit which melody is more complex, and presumably, more difficulty to dictate.

* FIGURE 1 -- Melody with 8 Bars, functional accidentals (V/V, V/IV)

* FIGURE 2 -- Same sets of notes rearranged 

While I reserve an extended discussion of what features might characterize why one melody is more difficult to dictate than the other  for this chapter, I assume that these melodies differ in their ability to be dictated in some fundamental way when performed in a similar fashion.
Additionally, many readers of this dissertation can draw from anecdotal evidence of their own as to how students at various stages of their aural training might fair when asked to dictate both melodies.
For some, melody Y might be overwhelmingly difficult.

> So what? 

In fact, melody Y might be overwhelmingly difficulty for the vast majority of musicians.
Students in particular are quick establish if they believe that a melody they are being tested on is too difficult.
From a pedagogical standpoint, we as educators need to be able to know how difficult melodies are to dictate when to our students in order to ensure a degree of fairness when assessing a student's performance.
While of course with each student there are inevitably many variables at play in aural skills instruction ranging from personal abilities, to the goals of the instructor in the scope of their course, there are benchmarks that students are expected to be able to complete throughout their education.
As students progress they are expected to be able to dictate more difficult melodies, yet exactly what makes a melody complex and thus difficulty to dicatate is often left to the expertise and intuition of a pedagogue.

> What I plan on doing

In this chapter I examine how tools from computational musicology can be used to help model an aural skills pedagogue's notion of complexity in melodies.
First, I establish that theorists agree on the differences in melodic complexity using results from a small survey of XX aural skills pedagoges.
Second, I explore how both static and dynamic computationally derived abstracted features of melodies can be used to approximate an aural skills pedagogue's intuition. 
Third and finally, I use evidence afforded by research in computational musicology to posit that the distributional patterns in a corpus of music can be strategically employed to create a more linear path to success among students of aural skills.
I demonstrate how by combining evidence from the statistical learning hypothesis, the probabilistic prediction hypothesis, and a newly posited distributional frequency hypothesis, can explain why some musical sequences in a melody of a certain complexity are easier to dictate than others.
Using this logic, I then create a new compendium of short melodies, sorted by their perceptual complexity, that can be used for teaching applications.

## Agreeing on Complexity

> Content matters, as does order

Returning to melodies X and Y from above, an aural skills pedagogue most likely has an intution to which of the two melodies X or Y would be easier to dictate.
Melody X exhibits a predictiable melodic synatax and phrase structure, the chromatic notes resovle within the conventions of the Common Practice period, and many of the melodic motives outline and imply a harmony based on tertian harmony.
On the other hand, Melody Y's syntax does not comform the the conventions of the common practice music and does not imply any sort of underlying harmony.
The durations of the rhythms appear irregular and the melody implies an uneven phrase structure.
Yet both melodies X and Y have the exact same set of notes and rhythms.
Though despite these content similarities, it would be safe to assume that melody X is probably much easier to dictate than melody Y assuming both were to be played at the same tempo and instrumentation. 

> People agree on difficulty 

In fact, aural skills pedagoges tend to agree for the most part on questions of difficulty of dication.
To demonstrate this, I surveyed XX aural skills pedagogues who have all taught at least two years of aural skills at the University level asking them questions presented in TABLE X on a sample of XX melodies found in the a commonly used sight-singing text book [@berkowitzNewApproachSight2011].
The survey had questions that specficially were designed to gauge their appropriateness for use in a melodic dictation context.

Questions included:

-----------------------
Table
1. What semester of Aural Skills do you think this melody is appropriate for?
2. How many times do you think this melody should be played considering the difficulty you noted in your previous  question?
3. Please rate how difficult you believe this melody to be for the average second year undergradaute at your institution using the slider provided. A 0 should indicate 'Very Easy' and a 100 should indicate 'Almost impossible'.
4. In your own subjective opinion, how musical do you believe this melody to be?
5. Is this melody familiar to you?
----------------------

Creating the survey I...
* Who it was sent out to (participants)
  - current institution
  - age of instructor 
  - number of years teaching aural skills
  - fixed vs moveeable do vs la based minor 
  - Instrument most amount of professional training on
  - Degree (Theory, performance)
* Asked X questions
  - see table
  - melodies came from Berkowitz textbook
  - sampled 15 melodies from 481
  - 

Overall, the sample exhibited a _____ degree of inter-rater reliability as measured by THIS STATISTICX^[Reference here about what is good and what is bad.]
Plotting the respondant's answers across the textbook the melodies were taken from, with the book progressing from less to more difficult, there is a trend among pedagoges to AGREE ON THE SIMPLER ONES THEN HAVE MORE DIAGREEMENT LATER ON? 
Central to my argument is a VERY LINEAR TREND of rating of complexity that correlate with both PAGE NUMBER from the textbook that it was drawn from, as well as an even better fitting model of THE EXACT NUMBER OF THE MELODY.

* Charts on that here 

MORE DISCUSSION HERE AFTER LOOKING AT DATA.

Taken together, both anecdotal and evidence for this survey suggest that aural skills pedagoges tend to agree on how difficult a melody is for use in an aural skills setting.
This sense of difficutly or complexity tracks as the book progresses, but to attribute the cause of a melody being difficult as its position in the book would be making a pretty hilarious error. 
The rest of this chapter investigates how computaionally derrived tools can help inform aural skills pedagogy.
In order to provide a sense of validity to the measure, I use the expert answers from the survey as the ground truth for the computational models.^[Do I have to explain what ground truth is?]

## Modeling Complexity

> What is complexity? 

The ability to quantify what theorists generally agree to be melodic complexity depends on distilling complexity into its component parts.
Earlier, when comparing melodies X and Y, some of the features put forward that might contribute to this measure were features such as note density, the melody's rhythm, what scale the melody draws its notes from, and how tonal the melody might be percieved. 
Some combination of these component features presumably make up the construct of complexity.

> History of complexity from melodies

Attempting to use features of a melody to to predict how well a melody is remembered has a long history.
In 1933, Ortmann put forward a set of melodic determinants that he asserted predicted how well a melody was remembered.
These features such as a melody's repeition, pitch-direction, contour (conjunct-disjunct motion), degree, order, and implied harmony (chord structure) were deemed to affect the melody's ability to be remembered [@ortmannTonalDeterminantsMelodic1933].

Pedagoges since Ortmann such as [@pembrookInterferenceTranscriptionProcess1986; @taylorStrategiesMemoryShort1983] have expanded on this research and concluded that ________.

Not only have researchers in music education attempted to quantify complexity, but work this type of work appears in music psychology.

* Harrisoon etal 2016
* References from Harrison 
* Baker 2017

Each of these examples operationalizes some feature of the melody with a numberical stand in.
These features are often refered to as abstracted features.
An abstracted feature can be either a quantitative or qualitiative observable feature of a melody that is assumed to be perceptually salient to the listener.
Abstracted features are often difficult to quantify with the traditional tools of music analysis.
Often, these abstracted features come inspired from other domains like computational linguistics.

To given an example of an abstracted feature, perhaps one of the most popular features in recent decades is the normalized pairwise variability index or nPVI.
The nPVI began as a measure of rhythmic variablility in langauge [@grabeDurationalVariabilitySpeech].
Shown below, the nPVI quantifies the amount of durational variability in language.
It works by comparing the variabilty of vowle lenght compared to syllable length 

$$\nPVI = 100 * [\sum_{k=1}^{m-1} | \frac{d_k - d_{k+1}}{(d_k + d_{k+1})/2}/(m-1)] $$

where M is the nubmer of vowels in an utterance and dk is th durtaiotn of the kth item. [@vanhandelRoleMeterCompositional2010]

In lingusitics, the nPVI has been used to deliniate quantiatve differces between stress and syllable timed langauges.
Recenlty in the past decade, music science researchers have used the nPVI to attempt to investigate claims about the relationship between speeach and laguage  [@danieleINTERPLAYLINGUISTICHISTORICAL2004; @patelStressTimedVsSyllableTimed2003; @vanhandelRoleMeterCompositional2010; DAN PAPER W KV].
While results are mixed regarding the nPVI's predictive ability and some people argue against nPVI (Deconstructing the nPVI: A Methodological Critique of the nPVI as Applied to Music When it comes out), it does serve as a very good example of a comuputationall derrived measure.
Just like summerizing the range of a melody by subtracting the distance between the lowest and highest notes, the nPVI summerizes a phrase and importantly assumes that this measure is representive of the entire phrase the calcuation was performed upon.

> Getting into Features 

In computational musicology, these features of melodies can generally be classified into two main types: static and dynamic features.
Static features compute a summary measure over the entire melody while dynamic features calculate values for each event onset in a melody.

One of the most complete set of static computational measures as applied to music perception come from Daniel Mullensiefens' Feature ANalysis Technology Acessing STatistics (In a Corpus) or FANTASTIC toolbox [@mullensiefenFantasticFeatureANalysis2009].
According to FANTATIC's techncial report, 

> "FANTASTIC is a program...that analyzes melodies by computing features The aim is to characterise a melody or a melodic phrase by a set of numerical or categorical values reflecting different aspects of musical structure. This feature representation of melodies can then be applied in Music Information Retrieval algorithms or computational
models of melody cognition." (pp. 4)

Drawing from fields both central and perphircal to music science, FANTASTIC computes a collection of 38 features to analyze features of melodies and joined a large and continuing tradition of analyzing music computationally [@lomaxCantometricsApproachAnthropology1977 ;@eerolaExpectancySamiYoiks2009; @huronHumdrumToolkitReference1994; @lartillotMatlabToolboxMusical2007; @lomaxCantometricsApproachAnthropology1977; @mcfeeLibrosaAudioMusic2015; @steinbeckStrukturUndAhnlichkeit1982].
Addittionally, FANTASATIC also provides a framework for comparing the features of a melody with a parent corpus from which the melody belongs.

> Back to Aural and applications

Returning to the Aural Skills classroom, many of these features can be used to approximate the intutions of complexity as agreed upon by theorists.
Below, I SHOW A SERIES OF PLOTS WHERE the continously measured abstracted features of FANTASTIC are plotted against the measures of perceieved complexity and difficulty of expert aural skills pedagoges with their respective correlations in TABLE X.

* GIANT FIGURE HERE

* GIANT TABLE HERE

From this, it becomes evident that some features like __________ and ________ succede quite well in approximating the rated complexity measures, while others like __________ and ________ do not.
I suggest that the reasons that ________ measures are sucessful in explainig is because ___________________.

In modeling this problem univariatly, it quicly becomes evident that no single static measure from FANTASTIC is able to complete mirror that of the complexity measrues.
Following past research [@bakerPerceptionLeitmotivesRichard2017; @harrisonModellingMelodicDiscrimination2016], in order to get a more accurate measure of complexity that mirrors a theorist's intution, it is possible to use principle components analysis to combine several measures of complexity into one single measure.
One reason this approach has been sucessful in the past computatational literature is that many of the abstracted features output by FANTASTIC are collinear.
Pratically, this means that it is very hard to change one aspect of a melody without affecting others. 
Due to the high degree of collinearity, it then becomes possible to reduce the amont of dimensions in the data and begin to approximate this notion of complexity.

-- Regression ups R2 hopefully 

Given the increase in model prediction, 

Hopefully at this point, I can make the argument that I am getting quite close at fully explaining the variance in ratings.
Finally, using the features of FANTASTIC, I can also use a random forrest method (LIKE THESE DANIEL PAPERS) to use some machine learning methods to see what best explains this data.

USING A .... details of Random Forrest here......

And importanly..... Variable imporacne plot which works by running multiple models and seeing how much variance is accounted for when the model is left out.

We see that X Y Z are of highest importance, and this corroborates literature from other FANTASTIC measures that say XYZ.

This is important for pedagogy, this can be used to help provide objective measure of difficulty.
Can also be a starting point for work on linking these various features with listener response.
And thus help people desgin curricula and also then better understand human pecerception and role of melody in the aural skills clasroom. 

Though while sucessful at modeling, using various linear combinations of these static abstracted features still assumes that listerns experience melodies in some sort of perceptual suspended animation. 
In order to have more phenomenologically approriate model that incorporates computainoally derived features, it is important to turn to dynamic models of music perception.

### Dynamic 

The Information Dynamic of Muscic (IDyOM) model of Marcus Pearce is a computational model of auditory cognition [@pearceStatisticalLearningProbabilistic2018a].
IDyOM works by .... [@pearceAuditoryExpectationInformation2012; @pearceConstructionEvaluationStatistical2005; @pearceStatisticalLearningProbabilistic2018a]
Unlike measures from FANTASTIC, that calculate summary statistics on melodies, IDyOM works by calculating the expectancy of an event based on parameters that it was trained on. 
As mentioned in Chapter 1, IDyOM is based both on the statistical learning hypothesis and probabilistic prediction hypothesis.
According to Pearce, the Statistical Learning Hypotheis states that:

> musical enculturation is a process of implicit statistical learning in which listeners progressively acquire internal models of the statistical and structural regularities present in the musical styles to which they are exposed, over short (e.g., an individual piece of music) and long time scales (e.g., an entire lifetime of listening). p.2 (Pearce, 2018)

The logic here is that the more an individual is exposed musical material, the more they will implicitly understand it which leads the corroborating probabilistic prediction hypothesis which states: 

> while listening to new music, an enculturated listener applies models learned via the SLH to generate probabilistic predictions that enable them to organize and process their mental representations of the music and generate culturally appropriate responses. p.2 (Pearce, 2018).

Given the fact that IDyOM makes its calculations based on a series of n-grams that the model is trained on, IDyOM is able to output measures of expectedness for each symbolic token used in its calculations.

As detailed in a summary review article on IDyOM by Pearce, the has been sucessful at modeling 

> accurately Western listeners’ melodic pitch expectations in behavioral,
physiological, and electroencephalography (EEG) studies using a range of experimental designs, including the probe-tone paradigm visually guided probe-tone paradigm a gambling paradigm, continuous expectedness ratings, and an implicit reaction-time task to judgments of timbral change. 

Additionally, Peace notes some of IDyOM sucesses in modeling beyond expectation, including sucesses in modeling emotional experiences in music, recognition memory, perceptual similarity, phrase boundary perception and metrical inference.
Importnatly, Pearce also claims that 

> A sequence with low IC is predictable and thus does not need to be encoded in full, since the predictable portion can be reconstructed with an appropriate predictive model; the sequence is compressible and can be stored efficiently. Conversely, an unpredictable sequence with high IC is less compressible and requires more memory for storage. Therefore, there are theoretical grounds for using IDyOM as a model of musical memory.

Peace notes four studies [@bartlettRecognitionTransposedMelodies; @cohenRecognitionTransposedTone1977; @cuddyMusicalPatternRecognition1981; @halpernAgingExperienceRecognition1995] that show that more complex melodies are more difficult to hold in memory. 
This theoretical assertion and select empirical findings have important ramifications for the aural skills classroom. 
In a dictation setting, melodies that are more expected should tax memory less, thus making them easier to remember and dictate. 
If I assume that more expected melodies are easier to remember, then it follows that the informaiton content measures of expectedness can then be used in melodic memory.
Taken together with the above statistcal learning hypothesis and probabilistic prediction hypotheiss, I then put forward a new hypotheis: the frequency facilitaiton hypotheisis. 

## Frequency Facilitation Hypothesis

> Define Logic

The frequency facilitation hypotheis makes two important assumptions that rely on both the statistical learning hypotheisis and the perceptual facilitaiton hypothesis.
The first is that humans learn melodies via the means predicted by the statistical learning hypothesis.
Melodic informaiton that people are exposed to more frequently will be more expected.
This assertion results from the probabilistic prediciton hypothesis.
Thus, given a sequence any set of notes, the frequency facilitation hypothesis posits that the effeciency in which a melody is processed in memory is related propoational to its degree of expetedness when quantified in information content.

From this hypothesis generates a series of testiable predcitions that can be investigated to verify its versimilitude. 
The first is that melodic patterns that occur more frequently in a corpus will be be easier to remember than those occuring less frequenlty.
To test this, we can look at various series of n-grams in a corpus to see model this.
In the following two sections, I explore this assertion and then show how this can be applied in the aural skills classroom. 

### Distributional Patterns in Corpus

In order to test this prediction, I extracted a set ten examples of bi, tri, quint, grams from a corpus of sight singing melodies intorduced in the next chapter.
Ten examples of each n-gram were sampled from the top and bottom 10% of the n-grams distribution in the corpus. 
The query was conducted by first translating the entire corpus to sofedge degrees, cleaned of GLiD, and meta information, then summarized. 
Code used to generate the query can be found in the dissertation appendix. 

The melodies are plotted in TABLE X

Gram | Melody | Low Frequnecy | High Frequency
-----|--------|---------------|----------
2    | Name   | Melody | Melody 
2    | Name   | Melody | Melody 
2    | Name   | Melody | Melody 
2    | Name   | Melody | Melody 
2    | Name   | Melody | Melody 
3    | Name   | Melody | Melody 
3    | Name   | Melody | Melody 
3    | Name   | Melody | Melody 
3    | Name   | Melody | Melody 
3    | Name   | Melody | Melody 
5    | Name   | Melody | Melody 
5    | Name   | Melody | Melody 
5    | Name   | Melody | Melody 
5    | Name   | Melody | Melody 
5    | Name   | Melody | Melody 

From the table, we can use intutiion to say that in the context of C Major, melodies appearing in the high frequency column might b easier to remember and dictate, especially in the context of Karpinksi's short-term musical memory than those in the low frequency table. 
These melodies could also be used then in a testing stituion.

* Write here about behavioral experiment to do that????

### Memory Facilitation 

Predictions here OR add in mini experiment that will be test for ISMIR paper.

go for further psychology experiemnts in this, 
lays basis for the computational model
and more direct pedagogical applicaitons are discussed below


### Peagogical applcation

So given the veracity of the frequency facilitaiton hypothesis, how might this information (derrived from comptuaitonal measures) be implemented in the classrom?

> State the general problem

In my experience as an Aural Skills pedagogue, students often belive that the problem with aural skills is that it progresses too quickly. 

* Miriam Idea 

> Can use static features of a melody to gauge difficulty 

> But really could also reorganize melodies based on cumulative IC (which IDyOM gives)

> Actually, if I do that, is this just overall best model fit to talk about music theorist intution? 

> But in addition to re-sorting melodies as ecological, could also use them as small gorups

> these could be then sorted based on small chunks and used in progressive loading

> Even follow IRT modeling and create adaptive testing for app or wahtever (hello post doccc)

> I give an example of this in Appedix
> Train corpus on all tonal melodies, then extract out ever n-gram
> then sort them
> Creates giant combinatorial explosion of melodic snippets descend arragned by IC 
> Students could eventually learn this in order
> then would feel like they are not overloaded 
> Futre work would also maybe pit two ways of treating arual skills against each other
> Just ecological 
> Just snippet
> combintaiotn of two as supplment 


> This is also now a serious path of inquiry for music peception resrach imo 

## Chapter Conclusions

In this chapter I have demonstrated how tools from computational musicology can be used as an aide in aural skills pedagogy.
After first establishing the extent to which aural skills pedagogues on various melody parameters, I then show how two families of computationally derrived features can stand in for a pedaguges intution.
First, using the FANTASTIC toolbox, I show how different combintations of static abstracted features can help explain theorists agreed upon complexity.
This first will help with selection of melodies and also provides insights as to which features of the melodies contribute most to percieved difficutly.
Second, I demonstrated how assumptions derived from the IDyOM framework can serve as a basis for the intutions of why smaller sequences of notes within melodies are more or less difficult to dictate.
Using the logic that sequences that are easier to process are more expected, and that computed measures of information content can be used as a proxy for memory, I show that it follows that given the sequence of an N lenght melody, the ease of dictaiton that it loads on memory is relative to both its degree of expectednes quantified in terms of informaiton content and link it back to hte corpus by linking THAT to it's n-gram distribbutional freuqency. 
This chain of thinking then allowed me to put forward a new sequence of melody segments that can be arragned, like other theory textbooks, in terms of their increasing complexiy.
I argue that using this smaller, snippit approach, will allow students to not be overwhelmed in their learning by taking a more linear path to dictation, before moving on to more more ecologically valid melodies.
I finish by disucssiong how this might be implemented in the classroom.


