# Hello, Corpus


## Rationale 


One of the key findings of any scientific discovery is the ability to reproduce the finding.

In this chapter, I introduce a new corpus of sight-singing melodies based on the the pedagogical text "A New Approach to Sight Singing" [@berkowitzNewApproachSight2011].
The corpus contains 783 monophonic melodies that have been digitially encoded in the kern format [@huronHumdrumToolkitReference1994] and contain both melodies specifically composed for use in the Aural Skills classroom and examples of melodies from outside musical literature. 
After introducing the corpus, I compare the Sight-Singing corpus with the Essen Folk Song [@schaffrathEssenFolkSong1995] collection in order to highlight the degree of variability with musical features in a corpus.


* COmputational musicology needs corpora
* Here is a history of that
* And it's important for this to be representative
* What do i think rrepresntaive means

## History And Why It Matters 

- People have been encodign music for a while 
- Began in 1960s
- Important to think about what people were into then
- Lots driven by funding bodies and having focus on global quesitons
- Lots driven by other factors?
- Eventually see people getting into Lomax and Savage world
- This is obvious overlap with comparative and ethonomusicology
- tensions addressed by savage
- going to happen no matter what haha
- 

> Important for music research to have new data

## Representation of Corpora 

- Many of the studies in the past have taken general historical approach to corpus
- This is different than people who see it more as representation of behavior
- For example look at all the Pat Savage stuff and his new article 
- And then we have the idea that a corpus can be trained to be representation of cognition
- But in statistical parlance, it's really what we are thinking of them as
- Useful to think about musical data and what they represent
- Take this ANOVA paper that basically has just come to me here by Gelman 

- In historical context generally wrong to think of data as being re-generated
- No more beehtoven 
- Fixed effects are assumed constant across individuals
- Often taken as something like Gender or Age 
- Can be either X or Y, that's it 
- We see this kind of thinking in these corpus papers 
- Would also see this like in that genre type paper 

- In the music as behavior ala Savage school 
- Idea is that over the course of time depending on agency, can model it with features changing
- Historical interest in this with the broadside ballads
- People in the west have done thi
- Savage notes that people in the east have done this 
- Mixes both humanities style historicism with quasi-scientific modeling of transmission

- Then lastly we can use corpus to represent cogniitive states
- need active process for this
- Much like NLP and textbook
- But isntead we have that with IDyOM
- Idea here is that the corpus is representing something manifestation of cognition 
- And we need to be able to track all these schema (Dom and Bryn)

- so when we run a test, need to think more about generative assumptions
- And of course this leads into abductive process
- but of course ian cross cognitive approach is best 
- Historical is bad on category, tho idk if people do that
- behiavoral is messy 
- but it interacts with cognition
- cog models are sucessful
- and imporantly, if they are LIKE LINGUISTIC CONVERSATION 
- Then when we swap them out, should get same results, models robust
- Also because taking this approach also links to general theory of human behavior
- SLH, PPH, Manifestation in music
- So given all that, here is a new corpuS

So first think when people use corpora they need to be very clear on what they think their corpus is representing.
And thus the claims that it can make
- Harmonic analysis is especially guilty of this
- Take for example Chris White and Quinn paper that just Machine learns
- Know that models are dependent on data
- Not only that, but how the data is encoded refelects epistomological assumptions
- MEI captures as we notate it
- But returnt to textbook here based on 

- empiricist as actually occurs
- ratonalists langauge or harmony module of the mind 
- closer to chomsky linguitic compotence -- knowledge of structure in the midn
- linguistic performance -- what affordances fuck this up 

Generative linguistics has argued that one can
isolate linguistic competence and describe it in isolation, while empiricist
approaches generally reject this notion and want to describe actual use
of language.

chomsky is categorical -- yes no
better to go probabsilitic 




- Example of this is that 


## Corpus Introduction 

## Corpus Comparision

History of the Essen Folk Song

- s


Imporantly, reperesents set of implicitly held musical undersanding.
End with discussion following London of "representative corpus"
People can now use this corpus for a lot of things. 

## Rationale

Corpus work helps inform how we see the world bc it generalizes.
This was first done in linguistics.
Paragraph here on gw book.
Note that there is general split between sylometery studies and using it for NLP.

Similar paths were taken in music.
We have the MP trajectory that he outlines.
Many of the early studies just summerise.
Though they are largely situated in Meyer idea that genre is complex system of relations.



Give basic summary statistics on the corpus.
Compare it as a corpus to essen.




-------------------------------

After make argument about two different types of corpora, say we have implicit
If it is implicit, follows that there should be some sort of overlap
kind of like a markov chain and leonard meyer.



* Point is to introduce corpus 
* Origin outside music, current state IN music, limitations
* Describe features of music in corpus
* Compare it to the features in the Essen Collection


Interesting point here is the scoping between what a corpsu represents.
On one side we can have the collected works of a dead musician.
Something like all of the trumpet solos of clifford brown.
Basically have a population here, tho incomplete.
Theoretically could have all the studio recordings, transcribe them, total collection.
While we could sample from this, problem is that the set is finite.
There is no recreating of more clifford brown solos since he died.

Could further zoom out and look at a genre.
This is very much like the Nick cook chopin studies.
Mirrored here with Shanahan's Debussy studies.
Also shanahan chord change studies
Idea here is that you are looking for changes over time.
But again with clifford, can't really re-do the 20th century.
Maybe find one or two more tunes, but no way to re write cultural conceptions.
Almost tautologically we have kept what we wanted and used that for our definition.

Zooming out even further we have corpora like the Essen Collection.
here it is meant to be represntitive of folk songs of Europe.
Presumably this is also bounded by space and time 
And it begs the question of should songs today be added to the Essen collection?
What does this corpus actually represent?

Societal conception of what our prototypes might derrive from?
Or Colleciton of folk songs for historical purposes? (Ala lomax, bartok, whatever)
At this level, represents the genre or style.

We see this assumption that these collections or styles are representing something we implicitly have in the work of MP IDyOM.
He trains his auditory computational model of cognition on a corpus that is limited in space and time, but then generalizes those probabilities into human behavior.

And the thing is that they are very sucessful.
We can look at the many things from Pearce 2018 where IDyOM is able to get it right.
Western, Jazz, Chinese music. 

So knowing that there is a move from the single dead composer to a cognitive conception of style.
Would be good to have digital representaitons of sytles in brain.
Could argue that sight singing melodies in the bel canto tradition follow this.
Of course there is cultural baggage with it.
But as stated in previous chapters, lots of people do sight singing and sight reading.
And these melodies presumably come from the same culture they train musicians for,

Interesting question as what it would mean to add a batch of sgiht sininging melodies ot other corpora.

But here it is, a corpus of XXX melodies.

### Why I don't follow a random sampling method

Also I will explicitly say here I don't follow a random sampling method as perscribed by London.
In his article comes to the conclusion that 300 or so pieces is needed for representive sample.
Show how the cannon needs to be connected to something perceptual.


** LONDON OF WHAT DOES IT MEAN TO BE REPRESENTIVE 
-- london suggests 300 pieces for classical music representation
-- says that the point is the build a corpus that is "broadly representative of the classical
composers, styles, and genres that are most familiar to the 21st century listener."
-- says that this then comes from what we hear 
--- JL deliniates between passive and active consumption 
-- point is that these sources "reflect our musical environment"
-- the implicit assumption being that works outside this sampling would be described as not belonging, but is that not really just a not natural category since if we were to decide that it did belong, it would get lumped in? Clearly the deliniating point here is that of questions of musical similarity and questions of musical similarity are questions of subjectivity. So have to realize with this loop that unless we can additionally provide external evidence that melodies are perceptually different, hard to maintain the borders of what the corpus represents. 

-- Also does this take into account that the listener would change based on exposure and training
-- get direct and indirect uses of classical music and sample from that 
-- def notes problems in sampling esp w value judgments and lenght of recordings

Matthews (2009) -- looking at american programming

Burden of learning to play the piece in terms of diversity?>? 


VOLUME 31 OF MUSIC PERCEPTION

Moving away from performance like live stuff or score based.


Also when assempling a representive corpus, if you have a lot from one genere where the music is very similar, would htat not be an example of having your residuals correlated?

And is there also an implicit assumption that there is something intrisic to each of these melodies that would allow them to be perceptually distiguishable from the other ones.
Style crossovers are very hard , things like post modern jukebox.

So instead I am introducing novel corpus of 600 melodies that are not tethered to a large cannon in the way that something like a London corpus, or Barlow and Morgenstern, or Essen would presumably be.
In the above context they come from small subcultre most related to bel canto singing.

I first describe the corpus as a whole.

Descriptive statistics.
Number of songs.
Lenghts of songs.
Key distributions.
facet wrap of tone profiles.

But then I compare this to the Essen folk song and Densmore and China.

Would be interested to know if you train an IDyOM model on three distinct corpora, will the melody from each of the corpus reflect the different expectationa values in terms of cultural difference.

Make the argument that all corpora are implicit genres.
Find that pearce paper about historical listening. 




